
if __name__ == '__main__':
    print_hi('Hello, Idealistas!')

import pandas as pd
pd.set_option('display.max_columns', None)
path = r'C:\Users\aimartins\OneDrive - Parfois, SA\Desktop\MDS6\es_home_sale_Madrid_2018.csv'
df = pd.read_csv(path, sep=";")

df.describe

from google.colab import drive

drive.mount('/content/gdrive')



import pandas as pd
from ydata_profiling import ProfileReport

df = pd.read_csv('/content/gdrive/Shareddrives/MDS+6 _IDEALISTA/DATA/es_home_sale_Madrid_2018 (1).csv', sep=';')

profile = ProfileReport(df)
profile



# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhbCg8RLzEhVt3paSSUfBaOGhrvffzAu
"""

import pandas as pd
pd.set_option('display.max_columns', None)

path = r'/content/es_home_sale_Madrid_2018.csv'
df_madrid = pd.read_csv(path, sep=";")

df_madrid.describe()

df_madrid[df_madrid['PRICE']==21000]

df_madrid[df_madrid['PRICE']==8133000]

"""FLOORCLEAN: ver si son con un andar"""

df_madrid[df_madrid['FLOORCLEAN']==-1]

df_madrid[df_madrid['FLOORCLEAN'].isnull()]

df_madrid[(df_madrid['CADDWELLINGCOUNT']==1) & (~df_madrid['FLOORCLEAN'].isnull())]['FLOORCLEAN'].unique()

df_madrid[(df_madrid['CADDWELLINGCOUNT']==1) & (~df_madrid['FLOORCLEAN'].isnull())]

#Tenemos el cadconstructionyear
df_madrid=df_madrid.drop(columns=['CONSTRUCTIONYEAR', "ADTYPOLOGYID", "ADOPERATIONID"])

#FLOORCLEAN no puede ser mayor que el

df_madrid[df_madrid['FLATLOCATIONID'].isnull()]

#Validar el orden del dataset
df_madrid[df_madrid.ASSETID == "A5166385142982428764"]

df_madrid[df_madrid['ASSETID'].duplicated(keep=False)]['ASSETID'].nunique()
df_madrid['ASSETID'].nunique()

perc_casos = df_madrid[df_madrid['ASSETID'].duplicated(keep=False)]['ASSETID'].nunique()/df_madrid['ASSETID'].nunique()

df_madrid.isnull().sum()

# from google.colab import drive


# !pip install pandas-profiling

# import pandas as pd
# from ydata_profiling import ProfileReport


# profile = ProfileReport(df_madrid)
# profile

numeric_columns = df_madrid.select_dtypes(include='number')

#preço médio por metro quadrado por bairro
#correlações entre os quartos e os banhos
import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(numeric_columns, annot=True, cmap='viridis', linewidths=.5)
plt.show()

sns.pairplot(numeric_columns,diag_kind='kde')